export const SUBMIT_ARTICLE="SUBMIT_ARTICLE";
export const GET_ARTICLE="GET_ARTICLE";
export const VIEW_ARTICLE="VIEW_ARTICLE";
export const REMOVE_ARTICLE="REMOVE_ARTICLE";
export const EDIT_CONTACT="EDIT_CONTACT";